### ISSUE TITLE
Improve the Polling command documentation

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-json#215]
Users have reported that the documentation describing the Polling commands is hard to understand. It should be rewritten to explain it more carefully (adding some examples in the process).

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/iotagent-json/pull/410 improves documentation.

Not sure if this fully covers the issue, but the documentation has changed quite a bit since 17 Jan 2017 :) so I think it's better to close this old issue and, if needed, open new ones with problems in the current documentation.
