### ISSUE TITLE
Possible bug in IOTAUtils.createConfigurationNotification() function

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-json#563]
It comes from @jason-fox feedback at https://github.com/telefonicaid/iotagent-json/pull/561#issuecomment-826849223:

> 
> 
> There is a mismatch in expectations with the updated notification. The IoT Agent Node lib supplies the following:
> 
> ```
> [
>   { type: 'string', value: '200', name: 'sleepTime' },
>   { type: 'string', value: 'ERROR', name: 'warningLevel' }
> ]
> ```
> 
> Under NGSI-v1 this is processed by `IOTAUtils.createConfigurationNotification()` to:
> 
> ```json
> {
>   "sleepTime": "200",
>   "warningLevel": "ERROR",
>  "dt": "20210426T151606"
> }
> ```
> 
> Under NGSI-v2 this is processed by `IOTAUtils.createConfigurationNotification()` to:
> 
> ```json
> { "0": "200", "1": "ERROR", "dt": "20210426T151606" }
> ```
> 
> Therefore the test can only be fixed if the expectation is not checked. I suspect this is actually a bug in the NGSI-v2 processing, since removing the `isCurrentNGSI()` check in `IOTAUtils.createConfigurationNotification()` fixes the two breaking tests but breaks others.
> 
> You could claim that the updated tests now run successfully, and this PR should just touch the tests. However someone should investigate what **should actually happen here** and whether:
> 
> a) The `IOTAUtils.createConfigurationNotification()` needs amending and the test expetcations elsewhere are wrong.
> b) The Test expectations I have amended just need aligning to the new format.

If it is a) then the this issue is about the bugfix. A PR will be done to implemente the fix.
If it is b) then the fix will be done in PR https://github.com/telefonicaid/iotagent-json/pull/561 and this issue closed without further actions.

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/iotagent-json/blob/55466abb1253c25d993a409497ee056c075048e1/lib/iotaUtils.js#L137-L153

**Comment by jason-fox** [comment]
> Maybe there is a problem related with ngsi version detection

Unfortunately no, quite the opposite. The code is correctly identifying the **updated** test as NGSI-v2 and hence following the `for` loop on line 142 rather than line 146. However the parsed payload in  `[{ name, value}, {name, value}]` format at this point, hence the reason I can "fix" this issue by removing the `if` clause.

Maybe someone can provision and configure a real device using NGSI-v2 and report back - does it want `[{ name, value}, {name, value}]` format or is a single object `{key1:value, key2: value}`



BTW,The same code can be found in the Ultralight "twin": https://github.com/telefonicaid/iotagent-ul/blob/master/lib/iotaUtils.js#L331

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-json/pull/571 (and also PR https://github.com/telefonicaid/iotagent-ul/pull/496 for the same problem in IOTA-UL)
