### ISSUE TITLE
None of the attributes should update on Orion if schema of IoTAgent device doesn't match

### ISSUE THREAD

**Issue by Arefina-NEC** [telefonicaid/iotagent-json#601]
**Problem**: IoTAgent sent an error 404 "DECVICENOTFOUND" but in Orion Context Broker data is updated for same measure.

**Description**: We have registered device on IoT Agent(port 4041) successfully. When we sent alert to that device through IoT Agent(port 7896) it was sent successfully but if we are sending extra attribute in the data-payload (other than attributes defined during registration/provision), it showed below error:
 {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:fEntity1","code":404}

The IoTAgent sent response 404 error code but  Orion attributes are updated with same payload.

**Steps to Reproduce:**

In this below example we have used  default properties like "explicitAttrs": false :

- Provision a device/group with a entity id: "fEntity1":
![image](https://user-images.githubusercontent.com/93588834/140024965-1e52be4a-7ca2-45a4-8945-1d29b71ddfaf.png)

- Sending measure to device "device001" with extra attributes:

![image](https://user-images.githubusercontent.com/93588834/140024853-54deff76-958c-42be-ac5b-6d3cd6164ecf.png)

![image](https://user-images.githubusercontent.com/93588834/140024373-3817f1d7-a595-4f5e-b30d-90a4930dbb3a.png)

The IoTAgent sent response 404 error code with error message " {"name":"DEVICE_NOT_FOUND","message":"No device was found with id:fEntity1","code":404}"

- Get the orion data for enity: "fEntity1"
![image](https://user-images.githubusercontent.com/93588834/140025604-cb11a405-8458-4b34-880a-c4215d83b36b.png)
 The attribute is updated while IoTagent send an error for same measure.
 
Thanks for your help! :)

We have raised same issue in Orion Community and please find below link of that issue:
https://github.com/telefonicaid/fiware-orion/issues/3988

**Comment by AlvaroVega** [comment]
Could you provide more information about how is the group configuration (service) of that device and how a measure is identifying that (by apikey? ) ?

**Comment by AlvaroVega** [comment]
`{"name":"DEVICE_NOT_FOUND","message":"No device was found with id:fEntity1","code":404}` is just an error in logs or just the response obtained when a measure is sent?

**Comment by Arefina-NEC** [comment]
Please find below curls commands to reproduce the problem:
- Service Provision: 
curl --location --request POST 'http://192.168.1.106:4041/iot/services' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: fservice' \
--header 'fiware-servicepath: /fpath' \
--data-raw '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ob",
     "cbroker":     "http://192.168.1.106:1026",
     "entity_type": "fEntity",
     "resource":    "/iot/json"
   }
 ]
}'

- Device Provision:

curl --location --request POST 'http://localhost:4041/iot/devices' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: fservice' \
--header 'fiware-servicepath: /fservicepath' \
--data-raw '{
"devices": [ {"device_id": "device01",
"entity_name": "fEntity1",
"entity_type": "fEntity",
"protocol": "IoTA-JSON",
"explicitAttrs": false,
"attributes": [
{ "object_id": "transactionId", "name": "transactionId", "type": "String" } ] }]}'


- Send measure to Device:


curl --location --request POST 'http://localhost:7896/iot/json?i=device01&k=4jggokgpepnvsb2uv4s40d59ob' \
--header 'Fiware-Service: fservice' \
--header 'Fiware-ServicePath: /fpath' \
--header 'Content-Type: application/json' \
--data-raw '{"transactionId": "t162431748007",
"newAttribute": "value"}'

- Get data from Orion:


curl --location --request GET 'http://localhost:1026/v2/entities' \
--header 'Fiware-Service: fservice' \
--header 'Fiware-Servicepath: /fpath'

>{"name":"DEVICE_NOT_FOUND","message":"No device was found with id:fEntity1","code":404} is just an error in logs or just the response obtained when a measure is sent?

This response obtained in both during error sent and in logs.
Please refer issue #3998, we have also mentioned this details there.

We are using NGSI v2. Please let us know in case of any other details are required.

**Comment by fgalan** [comment]
@Arefina-NEC could you test as @AlvaroVega did , please? I mean, without ` "cbroker": "http://192.168.1.106:1026"` in the service provisioning API call (you can set that same CB configuration in config.js or with an env var)

In addition, another important piece of information regarding your test would be the ITO Aagent version you are using. Could you provide this information, please?

Thanks!

**Comment by Arefina-NEC** [comment]
@AlvaroVega Could you please mention Which IoTAgent and Orion version you have used. We assumed that this functionality seems to be incorrect as data should not be updated on Orion if the schema of device not matched as  you have make "explicitAttrs" false during device provisioning.

@fgalan yes we have checked with without providing the "cbroker" in service provisioning, we were facing the same issue. 

We are using the IoTAgent version 1.17 but we have also checked for 1.19.0 version and the issue is same.

We want to add one more information that we have also checked by making "explicitAttrs" true during device provisioning, in this case extra attribute eliminated from the payload and registered attributes are forwarded to orion. The response received from IoTAgent to"200 OK" and  this functionality looks correct. But the functionality seems to be incorrect for "explicitAttrs": false as data should not be updated on orion if schema is not matched.

Our understanding is that the data payload should be rejected on IoTAgent in case there is an extra attribute in payload if the "explicitAttrs" false during device provisioning.

**Comment by Sunny-NEC** [comment]
@AlvaroVega @fgalan please share your  response on this issue.

**Comment by AlvaroVega** [comment]
@Sunny-NEC I was used latests versions of iotagent-json and orion, which in  Nov 18, 2021 where  a little more than  1.19.0  3.3.1 respectively, since where obtainer from master branch. Now are equivalent to 1.20.0 and 3.4.0

**Comment by fgalan** [comment]
> @Arefina-NEC could you test as @AlvaroVega did , please? I mean, without ` "cbroker": "http://192.168.1.106:1026"` in the service provisioning API call (you can set that same CB configuration in config.js or with an env var)

It would be great if you could do the same test that @AlvaroVega did (and which proved that it was working OK) in your environment to check if we are in a common ground.

**Comment by ayushi4** [comment]
> explicitAttrs": false



> I've being executing the following (and similar) secuence:
> 
> ```
> curl --location --request POST 'http://localhost:4052/iot/services' \
> --header 'cache-control: no-cache' \
> --header 'content-type: application/json' \
> --header 'fiware-service: smartcity' \
> --header 'fiware-servicepath: /' \
> --data-raw '{
> "services": [
> {
> "apikey": "4jggokgpepnvsb2uv4s40d59ob",
> "entity_type": "fEntity",
> "resource": "/iot/json"
> }
> ]
> }'
> ```
> 
> ```
> curl -i --location --request POST 'http://localhost:4052/iot/devices' \
> --header 'cache-control: no-cache' \
> --header 'content-type: application/json' \
> --header 'fiware-service: smartcity' \
> --header 'fiware-servicepath: /' \
> --data-raw '{
> "devices": [ {"device_id": "device01",
> "entity_name": "fEntity1",
> "entity_type": "fEntity",
> "protocol": "IoTA-JSON",
> "explicitAttrs": false,
> "attributes": [
> { "object_id": "transactionId", "name": "transactionId", "type": "String" } ] }]}'
> ```
> 
> HTTP/1.1 201 Created X-Powered-By: Express Fiware-Correlator: e2c54d6e-75cf-4454-9093-a0eeafcbc65c Content-Type: application/json; charset=utf-8 Content-Length: 2 ETag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8" Date: Thu, 18 Nov 2021 15:19:04 GMT Connection: keep-alive Keep-Alive: timeout=5
> 
> ```
> curl -i --location --request POST 'http://localhost:7897/iot/json?i=device01&k=4jggokgpepnvsb2uv4s40d59ob' \
> --header 'Fiware-Service: smartcity' \
> --header 'Fiware-ServicePath: /' \
> --header 'Content-Type: application/json' \
> --data-raw '{"transactionId": "t162431748007",
> "newAttribute": "value"}'
> ```
> 
> HTTP/1.1 200 OK X-Powered-By: Express Content-Type: application/json; charset=utf-8 Content-Length: 2 ETag: W/"2-vyGp6PvFo4RvsFtPoIWeCReyIC8" Date: Thu, 18 Nov 2021 15:23:57 GMT Connection: keep-alive Keep-Alive: timeout=5
> 
> ```
> curl -i --location --request GET 'http://localhost:10026/v2/entities' \
> --header 'Fiware-Service: smartcity' \
> --header 'Fiware-Servicepath: /'
> ```
> 
> HTTP/1.1 200 OK Connection: Keep-Alive Content-Length: 992 Content-Type: application/json Fiware-Correlator: a703a12c-4883-11ec-b1ed-0242ac110010 Date: Thu, 18 Nov 2021 15:24:42 GMT
> 
> [{"id":"fEntity1","type":"fEntity","TimeInstant":{"type":"DateTime","value":"2021-11-18T15:23:57.769Z","metadata":{}},"newAttribute":{"type":"string","value":"value","metadata":{"TimeInstant":{"type":"DateTime","value":"2021-11-18T15:23:57.769Z"}}},"transactionId":{"type":"String","value":"t162431748007","metadata":{"TimeInstant":{"type":"DateTime","value":"2021-11-18T15:23:57.769Z"}}}}]
> 
> and seems to works

@AlvaroVega How you are not getting 'Attribute not found' when sending additional attribute in the payload, while sending measures at Device.

**Comment by apurv-nec** [comment]
Please find the curl commands, with the output images:-

1.SERVICE PROVISIONING: -
Here we are provisioning our service as shown below using the curl request and also screenshot is attached to show that our device is provisioned properly showing 201 created in our response.
curl --location --request POST 'https://host/iot/v1.0/services' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: smartcity' \
--header 'fiware-servicepath: /' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48' \
--data-raw '{
"services": [
{
"apikey": "3jggokgpepnvsb2uv4s40d59ob",
"entity_type": "fEntity",
"resource": "/iot/json"
}
]
}' 

![image](https://user-images.githubusercontent.com/99782400/154200181-665ffc0e-16e9-4db3-971a-07ab3472bc3c.png)



2.DEVICE PROVISIONING:-
1.Now here we have registered our device schema on our IoT-agent using curl request and also a screenshot is attached to show that device is created properly showing 201 created in our response
2.Here,we have registered only one attribute transactionId in the schema.
curl --location --request POST 'https://host/iot/v1.0/devices' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: smartcity' \
--header 'fiware-servicepath: /' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48' \
--data-raw '{
    "devices": [
        {
            "device_id": "device01",
            "entity_name": "fEntity1",
            "entity_type": "fEntity",
            "protocol": "IoTA-JSON",
            "explicitAttrs": false,
            "attributes": [
                {
                    "object_id": "transactionId",
                    "name": "transactionId",
                    "type": "String"
                }
            ]
        }
    ]
}'t

![image](https://user-images.githubusercontent.com/99782400/154200227-f20d8877-dc47-4e21-833b-bd4f3b0539d2.png)

 
  

3.Sending alert to IoT-Agent

1.Now here we are sending alert to our IoT-agent in which we have assigned value to our attribute transactionId as t162431748007.
2.Please note here in the value of transactionId the last three digit is 007.
3. We have also attached screenshot saying 200 OK which means that the alert is send to IoT-Agent.
curl --location --request POST 'https://host/iot2/v1.0/json?i=device01&k=3jggokgpepnvsb2uv4s40d59ob' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-ServicePath: /' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48' \
--data-raw '{
    "transactionId": "t162431748007"
}'


![image](https://user-images.githubusercontent.com/99782400/154200249-6821cff2-0d52-410c-b159-d01295282470.png)

 
4.To check data from orion

1.Now here we wish to check whether the value of our attribute transactionId is updated in our context Broker orion or not.
2.We do the curl request and in the reponse (showing 200 status OK)we are able to see our value of transactionId is updated to t162431748007
3.screenshot is attached to prove the above points .Please also note that last 3 digits of transactionId here is 007.
curl --location -g --request GET 'https://host/orion/v2.0/entities?id=fEntity1' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-Servicepath: /' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48'

 
![image](https://user-images.githubusercontent.com/99782400/154200286-efab6b11-5320-4398-9063-abe07504afc8.png)


5.Sending alert to IoT agent
1.Now here we are again sending alert to IoT-Agent but here we are making 2 changes in the body of our alert.
2.The 2 changes are:
a. We have changed the value of our “transactionId”  attribute. The last 3 digits have been changed from 007 to 118.
b. Also an extra attribute “newAttribute” has been added to the alert body.
Both these above changes have been shown in the screenshot attached.
3.Now coming to response we can see in the attached screenshot we get status:404 Not found ,device not found .
Here we totally respect the response as the alert schema does not matches with the registered schema ,it returns us 404 not found response.
4.Now according to this our updated value of transactionId should not be reflected back in our contextBroker orion as the schema is not validated on iot-agent. Hence our next step will be to check data from orion(done in point 6)
curl --location --request POST 'https://host/iot2/v1.0/json?i=device01&k=3jggokgpepnvsb2uv4s40d59ob' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-ServicePath: /' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48' \
--data-raw '{
    "transactionId": "t162431748118",
    "newAttribute": "value"
}'


![image](https://user-images.githubusercontent.com/99782400/154200313-64b92118-d89d-4ecb-96ae-83adbdb657fb.png)

 
6.To check data from orion

1.Here we check the data from orion using the curl request.
2.As shown in the screenshot attached our value of transactionId is updated in orion as last 3 digits are being shown as 118.

curl --location --request GET 'https://host/orion/v2.0/entities?id=fEntity1' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-Servicepath: /' \
--header 'Authorization: Bearer 54dee292-37a7-3c5b-a3fa-54cc4a1b6b48'

![image](https://user-images.githubusercontent.com/99782400/154200350-bf75d7fb-f4fc-4b73-9537-da8fa6f19516.png)

 
CONCLUSION:
When IoT-Agent returns 404 response due to invalid schema and it fails to match with registered schema, Hence none of the attributes should update on Orion if schema of IoTAgent device doesn't match. But in this it is updating the values in orion and trigger the notification to the subscriber.


As suggested by @fgalan we have also updated the config.js in IoTagent as suggested, still it is showing the same result.

@fgalan as advised by you, we have followed the same steps as @AlvaroVega in our environment but we are still facing the same issue. Please find it in above description of the steps followed by us.

**Comment by mapedraza** [comment]
Please, next time, in order to ease us to check, post the request made directly to the component. It seems that you have kind of API manager + authentication system. Even more, the point of failure can be related with those extra components or they can give a different output message.

First I put the docker-compose file used to check it (note I am using the latest version available when writing this message):

<details> 
  <summary>docker-compose.yml</summary>

```YAML
version: "3.1"

volumes:
    mongodb: ~

services:
    iot-agent:
        image: telefonicaiot/iotagent-json:latest
        hostname: iot-agent
        container_name: fiware-iot-agent-601
        depends_on:
            - mongodb
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_MONGO_HOST=mongodb"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-json"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_APPEND_MODE=true"
            - "IOTA_PROVIDER_URL=http://iot-agent:4041"

    mongodb:
        image: mongo:4.2
        hostname: mongodb
        container_name: db-mongo
        ports:
            - "27017:27017"

    orion:
        image: telefonicaiot/fiware-orion:latest
        hostname: orion
        container_name: fiware-orion-601
        depends_on:
            - mongodb
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb
```
</details>

**Test 1**

1.SERVICE PROVISIONING

```BASH
curl --location --request POST 'localhost:4041/iot/services' \
--header 'cache-control: no-cache'  \
--header 'content-type: application/json' \
--header 'fiware-service: smartcity'  \
--header 'fiware-servicepath: /'  \
--data-raw '{
"services": [
{
"apikey": "3jggokgpepnvsb2uv4s40d59ob",
"entity_type": "fEntity",
"resource": "/iot/json"
}
]
}'
```


2.DEVICE PROVISIONING

```BASH
curl --location --request POST 'localhost:4041/iot/devices' \
--header 'cache-control: no-cache' \
--header 'content-type: application/json' \
--header 'fiware-service: smartcity' \
--header 'fiware-servicepath: /' \
--data-raw '{
"devices": [
{
"device_id": "device01",
"entity_name": "fEntity1",
"entity_type": "fEntity",
"protocol": "IoTA-JSON",
"explicitAttrs": false,
"attributes": [
{
"object_id": "transactionId",
"name": "transactionId",
"type": "String"
}
]
}
]
}'
```


3.SENDING DATA TO IOT-AGENT

```BASH
curl --location --request POST 'localhost:7896/iot/json?i=device01&k=3jggokgpepnvsb2uv4s40d59ob' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-ServicePath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
"transactionId": "t162431748007"
}'
```

Response:
```JSON
{}
```


4.TO CHECK DATA FROM ORION

```BASH
curl --location -g --request GET 'localhost:1026/v2/entities?id=fEntity1' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-Servicepath: /' 
```

Response:
```JSON
[{"id":"fEntity1","type":"fEntity","TimeInstant":{"type":"DateTime","value":"2022-02-16T13:36:34.984Z","metadata":{}},"transactionId":{"type":"String","value":"t162431748007","metadata":{"TimeInstant":{"type":"DateTime","value":"2022-02-16T13:36:34.984Z"}}}}]%       
```


5.SENDING ALERT TO IOT AGENT
```BASH
curl --location --request POST 'localhost:7896/iot/json?i=device01&k=3jggokgpepnvsb2uv4s40d59ob' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-ServicePath: /' \
--header 'Content-Type: application/json' \
--data-raw '{
"transactionId": "t162431748118",
"newAttribute": "value"
}'
```

Response:
```JSON
{"name":"ENTITY_GENERIC_ERROR","message":"Error accesing entity data for device: fEntity1 of type: fEntity"}%  
```


6.TO CHECK DATA FROM ORION
```BASH
curl --location -g --request GET 'localhost:1026/v2/entities?id=fEntity1' \
--header 'Fiware-Service: smartcity' \
--header 'Fiware-Servicepath: /' 
```

Response:

```JSON
[{"id":"fEntity1","type":"fEntity","TimeInstant":{"type":"DateTime","value":"2022-02-16T13:38:31.901Z","metadata":{}},"transactionId":{"type":"String","value":"t162431748118","metadata":{"TimeInstant":{"type":"DateTime","value":"2022-02-16T13:38:31.901Z"}}}}]%      
```

CONCLUSIONS:
This is the default behaviour for the component. You are trying to add a new attribute to an entity, having the following error:

```JSON
{"name":"ENTITY_GENERIC_ERROR","message":"Error accesing entity data for device: fEntity1 of type: fEntity"}
```

If needed to append instead of update, you can use the appendMode as describe [here](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/advanced-topics.md#configuring-operation-to-persist-the-data-in-context-broker-appendmode).

If you add the option `"IOTA_APPEND_MODE=true"` to the docker-compose file, you will not have any return error when doing the step 5 and the result from step 6 would be something like this:

```JSON
[{"id":"fEntity1","type":"fEntity","TimeInstant":{"type":"DateTime","value":"2022-02-16T13:50:00.143Z","metadata":{}},"newAttribute":{"type":"string","value":"value","metadata":{"TimeInstant":{"type":"DateTime","value":"2022-02-16T13:50:00.143Z"}}},"transactionId":{"type":"String","value":"t162431748118","metadata":{"TimeInstant":{"type":"DateTime","value":"2022-02-16T13:50:00.143Z"}}}}]
```

You can also have a look to the option `explicitAttrs`

So it seems there is no problem with the iota gent. Please let us know if this solve your situation or not. If yes, please, comment here and close the issue

**Comment by mapedraza** [comment]
@Arefina-NEC did you check the process I describe above? Did it solve your problem?
